#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────
#  cap-backup.sh — initialise CAP repo and back it up on a GitHub fork
# ─────────────────────────────────────────────────────────────────────
#  Phases (each can be run on its own):
#    init     git init + extend .gitignore + stage all + preview
#    slim     strip vendored 3rd-party + compiled outputs from staging
#    commit   first commit  (run after init/slim, after preview verified)
#    push     add fork remote, push branch, create + push tag
#    status   one-shot diagnosis of current repo state
#    all      run init → slim → commit → push with confirmation prompts
#
#  Every run mirrors stdout + stderr to a timestamped log under
#    logs/git-backup-<timestamp>.log
#  so you have a permanent record of every command and its output.
#
#  Configurable via environment variables:
#    CAP_REPO_DIR     repo root             (default: this script's dir)
#    CAP_FORK_URL     fork remote URL       (default: SSH form below)
#    CAP_FORK_HTTPS=1 use HTTPS not SSH     (default: SSH)
#    CAP_BRANCH       branch name           (default: main)
#    CAP_TAG          tag name              (default: v0.1-gui-snapshot)
#    CAP_DROP_GLAUBER drop nuclear .dat too (default: 0 = keep them)
# ─────────────────────────────────────────────────────────────────────

set -u

# ── 1. Locate the repo root (= dir containing this script) ──────────
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
REPO_DIR="${CAP_REPO_DIR:-$SCRIPT_DIR}"

[[ -d "$REPO_DIR" ]] || { echo "ERROR: REPO_DIR=$REPO_DIR does not exist" >&2; exit 2; }
cd "$REPO_DIR" || exit 2

# ── 2. Configuration ────────────────────────────────────────────────
FORK_SSH="git@github.com:Oveissheibani/CAP8.0.git"
FORK_HTTPS="https://github.com/Oveissheibani/CAP8.0.git"
if [[ "${CAP_FORK_HTTPS:-0}" == "1" ]]; then
    FORK_URL="${CAP_FORK_URL:-$FORK_HTTPS}"
else
    FORK_URL="${CAP_FORK_URL:-$FORK_SSH}"
fi
BRANCH="${CAP_BRANCH:-main}"
TAG="${CAP_TAG:-v0.1-gui-snapshot}"
DROP_GLAUBER="${CAP_DROP_GLAUBER:-0}"

# ── 3. Logging — tee everything to a timestamped file ───────────────
LOG_DIR="$REPO_DIR/logs"
mkdir -p "$LOG_DIR"
TS="$(date +%Y%m%dT%H%M%SZ)"
LOG_FILE="$LOG_DIR/git-backup-$TS.log"
exec > >(tee -a "$LOG_FILE") 2>&1

# ── 4. Pretty headers ───────────────────────────────────────────────
hr()    { printf '════════════════════════════════════════════════════════════\n'; }
phase() { hr; printf '  %s\n' "$1"; hr; }
ok()    { printf '  ✓ %s\n' "$1"; }
warn()  { printf '  ⚠ %s\n' "$1"; }
fail()  { printf '  ✗ %s\n' "$1" >&2; exit 1; }
note()  { printf '    %s\n' "$1"; }

ask() {
    local prompt="$1"
    if [[ ! -t 0 ]]; then
        echo "  (non-interactive: assuming yes for: $prompt)"
        return 0
    fi
    local ans
    read -r -p "  $prompt [y/N] " ans
    [[ "$ans" =~ ^[Yy]([Ee][Ss])?$ ]]
}

show_preview() {
    local n_staged n_ignored
    n_staged=$(git status --porcelain | grep -cE '^[AM]')
    n_ignored=$(git status --ignored --porcelain | grep -c '^!!')
    echo
    echo "── Files staged    : $n_staged"
    echo "── Files ignored   : $n_ignored"
    echo
    echo "── Top 30 staged paths (alphabetic) ──"
    git diff --cached --name-only | sort | head -30
    [[ $n_staged -gt 30 ]] && note "..."
    echo
    echo "── Largest 10 staged files (anything > 5 MB is suspicious) ──"
    git diff --cached --name-only | xargs -I{} du -h "{}" 2>/dev/null \
        | sort -h | tail -10
    echo
    echo "── Total staged size ──"
    git diff --cached --name-only | xargs du -ch 2>/dev/null | tail -1
}

# ── 5. Phase functions ──────────────────────────────────────────────

phase_init() {
    phase "Phase 1 — git init + extend .gitignore + stage + preview"
    note "REPO_DIR : $REPO_DIR"
    note "BRANCH   : $BRANCH"
    note "LOG      : $LOG_FILE"
    echo

    if [[ -d .git ]]; then
        warn "$REPO_DIR is already a git repo — skipping 'git init'"
    else
        git init -b "$BRANCH" || fail "git init failed"
        ok "git init -b $BRANCH"
    fi

    if ! grep -q "Auto-generated by run-cap GUI" .gitignore 2>/dev/null; then
        cat >> .gitignore <<'EOF'

# Auto-generated by run-cap GUI
Grid/WSU/auto/
*.pyc
analyses/builder/__pycache__/

# User-uploaded reference docs (keep local, not in fork)
herwig7_install_prompt*.txt

# Saved presets (machine-specific)
my_preset*.json
EOF
        ok "extended .gitignore (auto-gen + presets blocks)"
    else
        warn ".gitignore already has the auto-gen block — leaving alone"
    fi

    git add -A || fail "git add -A failed"
    ok "staged $(git status --porcelain | grep -cE '^[AM]') file(s)"
    show_preview

    echo
    note "Next: review the file list above.  If anything shouldn't be"
    note "      tracked, run:    ./cap-backup.sh slim"
    note "When the list looks right, run:  ./cap-backup.sh commit"
}

phase_slim() {
    phase "Phase 1.5 — slim: strip vendored 3rd-party + compiled outputs"

    [[ -d .git ]] || fail "$REPO_DIR is not a git repo — run './cap-backup.sh init' first"

    # Extend .gitignore once (idempotent — checks marker first).
    if ! grep -q "fastjet-3.4.3/" .gitignore 2>/dev/null; then
        cat >> .gitignore <<'EOF'

# Vendored 3rd-party — re-download from upstream instead of bloating fork
fastjet-3.4.3/
fastjet-*/
pythia8[0-9]*/

# Belt-and-suspenders for compiled outputs / IDE droppings
*.dylib
*.a
*.app
*.swp
.cache/
.idea/
.vscode/
EOF
        ok "extended .gitignore (vendored + compiled-output blocks)"
    else
        warn ".gitignore already excludes fastjet-3.4.3/ — leaving alone"
    fi

    # Optionally drop the Glauber nuclear .dat files (off by default —
    # they're physics inputs, not code, but they're 12 MB).
    if [[ "$DROP_GLAUBER" == "1" ]]; then
        if ! grep -q "src/Glauber/.*plaintext" .gitignore 2>/dev/null; then
            cat >> .gitignore <<'EOF'

# Nuclear-density data — large physics inputs, archive separately
src/Glauber/*_plaintext.dat
EOF
            ok "extended .gitignore (Glauber nuclear .dat)"
        fi
    fi

    # Un-stage anything that the new rules now exclude.  Quietly tolerant
    # of paths that were never staged.
    local removed=0
    for path in fastjet-3.4.3 'fastjet-*' 'pythia8[0-9]*'; do
        if git rm -r --cached --ignore-unmatch "$path" >/dev/null 2>&1; then
            ((removed++)) || true
        fi
    done
    git rm --cached --ignore-unmatch '*.dylib' '*.a' '*.app' '*.swp' >/dev/null 2>&1 || true
    if [[ "$DROP_GLAUBER" == "1" ]]; then
        git rm --cached --ignore-unmatch 'src/Glauber/*_plaintext.dat' >/dev/null 2>&1 || true
    fi
    ok "un-staged vendored / compiled paths ($removed pattern hit)"

    # Re-stage, then preview
    git add -A
    show_preview

    echo
    note "Next:  ./cap-backup.sh commit"
    note "       (or re-run slim with CAP_DROP_GLAUBER=1 to also strip Glauber data)"
}

phase_commit() {
    phase "Phase 2 — first commit"
    [[ -d .git ]] || fail "$REPO_DIR is not a git repo — run './cap-backup.sh init' first"

    local staged
    staged=$(git diff --cached --name-only | wc -l | tr -d ' ')
    if [[ "$staged" -eq 0 ]]; then
        warn "Nothing staged."
        echo
        echo "  Last commit (if any):"
        git log --oneline -1 2>&1 || true
        return 0
    fi

    git commit -m "Initial snapshot — CAP 8.0 source + GUI overhaul

Source:
- src/ — CAP framework (Pythia/Herwig/HepMC3 generators,
  Single/Pair/Pair3D/NuDyn/PtPt/Spherocity analyzers, BF-per-stage,
  particle-decay control, ParticleEfficiency/Smearer primitives)
- DB/ — particle data, decay tables
- analyses/ — .ini composer + builder GUI
- cmake/ — Find modules for the full HEP stack

GUI (run-cap, build-ini-gui):
- Compose tab — generator config, particle filters, BF stages
- Subsample tab — N×M aggregation
- Wayne State tab — auto SLURM bundle generator (3-script model)
- Theme system with 18-slot palette + ~/.cap_theme.json persistence
- Save/Load full GUI state preset (cap_preset.py)
- Stable-particle widget (Tier-2, 58 species) + cτ cut for both gens
- Centred 135 px logo, vertical PanedWindow, scrollable everywhere

Docs:
- INSTALL_REPORT_HERWIG.md, LETTER_TO_HERWIG_AGENT_v1/v2/v3.md
- BF_PER_STAGE_PLAN.md, CODEBASE_MAP.md, BUILDING.md
" || fail "git commit failed"

    ok "committed"
    echo
    git log --oneline -1
    echo
    git show --stat HEAD | head -8
    echo
    note "Next: ./cap-backup.sh push"
}

phase_push() {
    phase "Phase 3 — add fork remote + push + tag"
    note "FORK_URL : $FORK_URL"
    note "BRANCH   : $BRANCH"
    note "TAG      : $TAG"
    echo

    [[ -d .git ]] || fail "$REPO_DIR is not a git repo — run './cap-backup.sh init' first"
    git rev-parse HEAD >/dev/null 2>&1 || fail "No commits yet — run './cap-backup.sh commit' first"

    if git remote get-url origin >/dev/null 2>&1; then
        local current
        current=$(git remote get-url origin)
        if [[ "$current" != "$FORK_URL" ]]; then
            warn "origin already points to $current"
            warn "(expected $FORK_URL)"
            if ask "Replace origin with the expected URL?"; then
                git remote set-url origin "$FORK_URL"
                ok "origin → $FORK_URL"
            else
                ok "leaving origin as-is — push will go to $current"
            fi
        else
            ok "origin already set to $FORK_URL"
        fi
    else
        git remote add origin "$FORK_URL" || fail "git remote add failed"
        ok "added origin = $FORK_URL"
    fi

    git remote -v
    echo

    echo "── Pushing $BRANCH to origin (this is the long step) ──"
    if git push -u origin "$BRANCH"; then
        ok "push succeeded"
    else
        fail "push failed.  Common causes:
            (a) SSH not set up — try CAP_FORK_HTTPS=1 ./cap-backup.sh push
            (b) HTTPS asking for password — use a Personal Access Token
                (Settings → Developer settings → PATs → Generate new token)
            (c) The fork already has commits — run 'git pull --rebase' first
                or recreate the GitHub fork as empty"
    fi

    if git rev-parse "refs/tags/$TAG" >/dev/null 2>&1; then
        warn "Tag $TAG already exists locally — skipping creation"
    else
        git tag -a "$TAG" -m "GUI overhaul + Wayne State bundle + presets"
        ok "tagged $TAG"
    fi
    if git push origin "$TAG" 2>&1; then
        ok "tag pushed"
    else
        warn "tag push failed (may already be on the remote)"
    fi

    echo
    hr
    ok "Fork backed up: ${FORK_URL%.git} (look for branch '$BRANCH', tag '$TAG')"
    ok "Log: $LOG_FILE"
    hr
}

phase_status() {
    phase "Repo diagnosis"
    note "REPO_DIR : $REPO_DIR"
    echo

    if [[ ! -d .git ]]; then
        warn "Not a git repo yet — run './cap-backup.sh init'"
        return 0
    fi
    ok ".git/ size: $(du -sh .git | cut -f1)"

    echo
    echo "── Branch / upstream ──"
    git rev-parse --abbrev-ref HEAD 2>&1
    git rev-parse --abbrev-ref --symbolic-full-name '@{u}' 2>&1 || \
        echo "  (no upstream — first push will set it)"

    echo
    echo "── Remotes ──"
    git remote -v 2>&1 || echo "  (none)"

    echo
    echo "── Working-tree summary ──"
    note "modified : $(git status --porcelain | grep -cE '^.M')"
    note "added    : $(git status --porcelain | grep -cE '^A')"
    note "deleted  : $(git status --porcelain | grep -cE '^.D')"
    note "untracked: $(git status --porcelain | grep -cE '^\?\?')"

    echo
    echo "── Last 5 commits ──"
    git log --oneline -5 2>&1 || echo "  (no commits yet)"

    echo
    echo "── Stash / tag count ──"
    note "stashes : $(git stash list 2>/dev/null | wc -l | tr -d ' ')"
    note "tags    : $(git tag 2>/dev/null | wc -l | tr -d ' ')"
}

# ── 6. Dispatch ─────────────────────────────────────────────────────
cmd="${1:-help}"
case "$cmd" in
    init)    phase_init ;;
    slim)    phase_slim ;;
    commit)  phase_commit ;;
    push)    phase_push ;;
    status)  phase_status ;;
    all)
        phase_init
        echo
        if ask "Phase 1 done — strip vendored 3rd-party (slim) before committing?"; then
            phase_slim
        else
            note "Skipping slim.  Snapshot will include vendored libs."
        fi
        echo
        if ask "Preview looks clean — commit now?"; then
            phase_commit
            echo
            if ask "Committed — push to fork now?"; then
                phase_push
            else
                note "Skipping push.  Run './cap-backup.sh push' when ready."
            fi
        else
            note "Stopping after preview.  Run './cap-backup.sh commit' when ready."
        fi
        ;;
    help|-h|--help|*)
        cat <<EOF
Usage: $(basename "$0") <phase>

Phases:
  init     Initialise repo, extend .gitignore, stage all, show preview
  slim     Strip vendored 3rd-party (fastjet-3.4.3/, etc.) + compiled outputs
  commit   First commit  (run after init+slim, after preview verified)
  push     Add fork remote, push branch, create + push tag
  status   One-shot diagnosis of repo state
  all      Run init → slim → commit → push with confirmation prompts

Environment overrides:
  CAP_REPO_DIR        repo root             (default: this script's dir)
  CAP_FORK_URL        fork remote URL       (default: git@github.com:Oveissheibani/CAP8.0.git)
  CAP_FORK_HTTPS=1    use HTTPS not SSH     (default: SSH)
  CAP_BRANCH          branch name           (default: main)
  CAP_TAG             tag name              (default: v0.1-gui-snapshot)
  CAP_DROP_GLAUBER=1  also strip Glauber    (default: 0 — keep them)
                      nuclear .dat files

Logs are written to ./logs/git-backup-*.log
EOF
        ;;
esac
