"""Pipeline construction + subprocess orchestration.

Takes the shared AppState dict, returns the ordered list of subprocess
argv's, and runs them in a worker thread streaming output into a queue.
Knows nothing about Tk.
"""
from __future__ import annotations

import math
import os
import queue
import re
import shutil
import signal
import subprocess
import tempfile
import threading
from pathlib import Path
from typing import Callable

from .panels.pythia import PythiaPanel
from .panels.herwig import HerwigPanel
from .rungs import cumulative_rungs
from . import resume
from . import mechanisms
from . import herwig_runner

PIPE_BIN_STUDY  = "bin/provenance-study"
PIPE_LADDER     = "cap-mechanism-ladder"
PIPE_PLOT       = "cap-provenance-plot"
PIPE_BIN_REPORT = "bin/provenance-report"


def _freshest(repo: Path, installed: str, build: str) -> str:
    """Return the newer of repo/<installed> and repo/<build> by mtime, so the
    GUI always runs the latest binary even if bin/ wasn't reinstalled from
    build-B.  Falls back to the installed path."""
    a, b = repo / installed, repo / build
    try:
        if b.exists() and (not a.exists()
                           or b.stat().st_mtime > a.stat().st_mtime):
            return str(b)
    except OSError:
        pass
    return str(a)


def study_binary(repo: Path) -> str:
    return _freshest(repo, PIPE_BIN_STUDY,
                     "build-B/src/EventHistory/provenance-study")


def report_binary(repo: Path) -> str:
    return _freshest(repo, PIPE_BIN_REPORT,
                     "build-B/src/EventHistory/provenance-report")


def shell_quote(s: str) -> str:
    if not s or any(c in s for c in " \t\"'$&|<>;()`\\"):
        return "'" + s.replace("'", "'\\''") + "'"
    return s


def commands_to_script(state: dict, cmds: list[list[str]]) -> str:
    """Render the exact argv list as a self-contained, copy-pasteable bash
    script that reproduces THIS GUI configuration on the terminal.

    Mirrors what Runner._run does: `cd` into the repo, and run the pdflatex
    stages from the reports directory (the Runner sets cwd for those).  Every
    other command already carries absolute or repo-relative paths, so a single
    `cd <repo>` up front makes the whole script runnable as-is."""
    repo = Path(state["repo"])
    reports_dir = Path(state["outdir"]).expanduser().resolve() / "reports"
    n = len(cmds)
    gens = ",".join(state.get("generators", ["pythia"]))
    events = state.get("events", "?")
    species = state.get("species", "211")
    chunk = int(state.get("chunk_events", 0) or 0)
    out = [
        "#!/usr/bin/env bash",
        "# ---------------------------------------------------------------",
        "# Generated by cap-provenance-gui — exact CLI for the current GUI",
        "# configuration.  Run it as-is, or hand it to someone to run.",
        f"#   generators={gens}  events={events}  species={species}"
        + (f"  resume-chunk={chunk}" if chunk else ""),
        f"#   stages={n}",
        "# ---------------------------------------------------------------",
        "set -e",
        f"cd {shell_quote(str(repo))}",
        "",
    ]
    for i, argv in enumerate(cmds, 1):
        cmd = " ".join(shell_quote(x) for x in argv)
        # pdflatex runs with cwd=reports/ in the Runner — wrap it the same way.
        if argv and argv[0] == "pdflatex":
            cmd = "( cd %s && %s )" % (shell_quote(str(reports_dir)), cmd)
        out.append("# [%d/%d]" % (i, n))
        out.append(cmd)
        out.append("")
    return "\n".join(out)


def commands_to_oneliner(state: dict, cmds: list[list[str]]) -> str:
    """Render the whole run as ONE chained command: `cd <repo> && c1 && c2 &&
    ... && cN`.  Paste it into a terminal in a single shot and it does exactly
    what the GUI's Run button would — no file to save, no comments.  The `&&`
    chaining gives the same stop-on-first-failure behaviour as `set -e`."""
    repo = Path(state["repo"])
    reports_dir = Path(state["outdir"]).expanduser().resolve() / "reports"
    parts = ["cd " + shell_quote(str(repo))]
    for argv in cmds:
        cmd = " ".join(shell_quote(x) for x in argv)
        if argv and argv[0] == "pdflatex":
            cmd = "( cd %s && %s )" % (shell_quote(str(reports_dir)), cmd)
        parts.append(cmd)
    return " && ".join(parts)


def materialise_pythia_cmnd(state: dict, dest: Path) -> Path | None:
    """Write the current Pythia config out as a .cmnd file.  Returns the
    path, or None if there are no lines to write."""
    lines = PythiaPanel.resolved_lines(state)
    if not lines:
        return None
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text("! generated by cap-provenance-gui\n"
                    + "\n".join(lines) + "\n")
    return dest


def materialise_herwig_in(state: dict, dest: Path) -> Path | None:
    """Write the current Herwig config out as a .in deck.  Returns the path,
    or None if there are no lines.  Used by the generator-comparison flow;
    actually running it needs the engine's HepMC3 input mode (COORD [B] needs)."""
    lines = HerwigPanel.resolved_lines(state)
    if not lines:
        return None
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text("# generated by cap-provenance-gui\n"
                    + "\n".join(lines) + "\n")
    return dest


_HERWIG_OK: bool | None = None


_SUPPORTED_FLAGS: dict[str, set] = {}


def supported_flags(study_bin: str) -> set:
    """Set of long options the provenance-study binary advertises in --help.
    Cached.  Lets the GUI stay resilient to an OLDER bin/provenance-study:
    flags it doesn't understand (e.g. --sphero-low on a stale binary) are
    dropped instead of crashing the run.  Empty set (probe failed) => don't
    filter, pass everything."""
    if study_bin not in _SUPPORTED_FLAGS:
        flags: set = set()
        try:
            r = subprocess.run([study_bin, "--help"], capture_output=True,
                               text=True, timeout=10)
            txt = (r.stdout or "") + (r.stderr or "")
            flags = set(re.findall(r"--[a-z][a-z0-9-]+", txt))
        except Exception:                              # noqa: BLE001
            flags = set()
        _SUPPORTED_FLAGS[study_bin] = flags
    return _SUPPORTED_FLAGS[study_bin]


def herwig_supported(study_bin: str) -> bool:
    """True if the provenance-study binary advertises a Herwig/HepMC3 input
    flag in its --help.  Cached.  Returns False for today's Pythia-only binary,
    so the comparison wiring stays dormant until Session A lands the engine
    flag — then it lights up automatically with no GUI change."""
    global _HERWIG_OK
    if _HERWIG_OK is None:
        _HERWIG_OK = False
        try:
            r = subprocess.run([study_bin, "--help"], capture_output=True,
                               text=True, timeout=10)
            txt = (r.stdout or "") + (r.stderr or "")
            _HERWIG_OK = any(f in txt for f in
                             ("--hepmc3", "--herwig-in", "--herwig"))
        except Exception:                              # noqa: BLE001
            _HERWIG_OK = False
    return _HERWIG_OK


def materialise_gen_rung_config(state: dict, gen: str, rung: dict,
                                dest: Path) -> Path:
    """Write a per-(generator, rung) config = the generator's base config plus
    the mechanism on/off lines for this rung, restricted to the mechanisms BOTH
    generators share (MPI, CR) so the comparison is apples-to-apples."""
    base = (PythiaPanel.resolved_lines(state) if gen == "pythia"
            else HerwigPanel.resolved_lines(state))
    extra = mechanisms.mech_lines(gen, rung.get("mechs", []),
                                  only=mechanisms.common_mechanisms())
    comment = "!" if gen == "pythia" else "#"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text("%s generated by cap-provenance-gui — %s rung '%s'\n"
                    % (comment, gen, rung.get("name", "")) +
                    "\n".join(list(base) + extra) + "\n")
    return dest


def _designed_rungs(state: dict) -> list[dict]:
    return [r for r in (state.get("ladder_rungs") or []) if r.get("name")]


def chunk_plan(events: int, chunk_events: int) -> list[tuple[int, int]]:
    """Split `events` into resumable chunks of <= chunk_events.

    Returns [(n_events_i, chunk_index), ...].  A single-element list means no
    chunking (run the whole thing as one).  chunk_events <= 0 disables it."""
    if chunk_events <= 0 or events <= chunk_events:
        return [(events, 0)]
    n = math.ceil(events / chunk_events)
    out, rem = [], events
    for i in range(n):
        ce = min(chunk_events, rem)
        out.append((ce, i))
        rem -= ce
    return out


def _chunk_dir(out_root: Path) -> Path:
    return out_root.parent / (out_root.stem + "_chunks")


def plan_units(state: dict) -> tuple[str, list[str]]:
    """Return (fingerprint, [study-output-root-paths]) for the current job —
    the units the resume mechanism tracks.  (The mechanism-ladder stage runs
    as one subprocess and is resumed by the tool itself; see COORD [B] needs.)"""
    outdir = Path(state["outdir"]).expanduser().resolve()
    generators = state.get("generators", ["pythia"])
    rungs = _designed_rungs(state)
    compare_mech = bool(state.get("compare_mechanisms")
                        and len(generators) > 1 and rungs)
    chunk_events = int(state.get("chunk_events", 0) or 0)
    events = int(state.get("events", 0) or 0)

    def _leaf(root: Path) -> list[str]:
        plan = chunk_plan(events, chunk_events)
        if len(plan) == 1:
            return [str(root)]
        cd = _chunk_dir(root)
        return [str(cd / ("c%d.root" % idx)) for _ce, idx in plan]

    if generators == ["pythia"]:
        units = _leaf(outdir / "runs" / "pions.root")
    elif compare_mech:
        # Rung-level units; a chunked Herwig rung resumes at chunk granularity
        # internally (build_commands), reported here at rung granularity.
        units = [str(outdir / "compare" / ("%s_%s.root" % (g, r["name"])))
                 for g in generators for r in rungs]
    else:
        # Single/multi generator standalone: each generator's compare root is
        # chunk-aware (Pythia and Herwig both honour chunk_events now).
        units = [u for g in generators
                 for u in _leaf(outdir / "compare" / (g + ".root"))]
    return resume.fingerprint(state), units


def run_warnings(state: dict) -> list[str]:
    """Human-readable warnings to surface before a run — chiefly that Herwig
    was selected but the current engine can't run it yet."""
    warns: list[str] = []
    study = study_binary(Path(state["repo"]))
    generators = state.get("generators", ["pythia"])
    if "herwig" not in generators:
        return warns
    hepmc = str(state.get("herwig_hepmc", "") or "").strip()
    if not herwig_supported(study):
        warns.append(
            "Herwig is selected but this provenance-study has no --hepmc3 input "
            "support (rebuild with CAP_ENABLE_HEPMC3=ON). Skipping Herwig"
            + ("." if generators == ["herwig"] else " — Pythia runs."))
    elif not hepmc and not herwig_runner.herwig_available():
        warns.append(
            "Herwig is selected and the engine supports --hepmc3, but no Herwig "
            "install was found (set HW_PREFIX, default "
            "/Users/oveissheibani/LocalHerwig/LocalHerwig/opt) and no .hepmc "
            "override is set. Skipping Herwig.")
    return warns


def write_run_manifest(state: dict) -> tuple[int, int]:
    """Persist the run manifest for this job (call on actual Run, not dry-run).
    Returns (completed_units, total_units) so the caller can report resume."""
    outdir = Path(state["outdir"]).expanduser().resolve()
    fp, units = plan_units(state)
    done = len(resume.completed_units(outdir, fp, units))
    resume.write_manifest(outdir, fp, units)
    return done, len(units)


def build_commands(state: dict) -> tuple[list[list[str]], list[str]]:
    """Compose the argv list for every stage that's enabled, plus any
    file paths the caller may want to surface (e.g. the Pythia .cmnd).

    Returns (commands, generated_files)."""
    repo: Path = state["repo"]
    outdir = Path(state["outdir"]).expanduser().resolve()
    runs_dir   = outdir / "runs"
    ladder_dir = outdir / "ladder"
    plots_dir  = outdir / "plots"
    reports    = outdir / "reports"
    pions      = runs_dir / "pions.root"
    pythia_cmnd = materialise_pythia_cmnd(
        state, outdir / "configs" / "pythia.cmnd")
    # Generator-comparison: when Herwig is selected, write its deck too so it's
    # ready for the engine's HepMC3 path (pending — see COORD [B] needs).  This
    # does not change the Pythia run that executes today.
    generators = state.get("generators", ["pythia"])
    herwig_in = (materialise_herwig_in(state, outdir / "configs" / "herwig.in")
                 if "herwig" in generators else None)

    # Species may be a single PDG ("211") or a comma-separated list
    # ("211,321,2212"); both flow verbatim to provenance-study /
    # cap-mechanism-ladder which know how to parse them.
    species_raw = state.get("species", "211")
    species = str(species_raw).strip() or "211"
    events  = str(int(state["events"]))
    ecm     = str(float(state["ecm"]))
    seed    = str(int(state["seed"]))

    par     = state.get("parallel", {})
    jobs    = str(int(state.get("_resolved_jobs", 1)))

    # Acceptance window + multiplicity-bin thresholds — audit fixes #3, #9.
    # Empty strings mean 'no override' so the C++ default applies.  We probe
    # the binary's --help so a flag it doesn't understand (e.g. --sphero-low on
    # an older bin/provenance-study) is dropped instead of erroring the run.
    _study_bin = study_binary(repo)
    _sup = supported_flags(_study_bin)

    def _ok(flag: str) -> bool:
        return (not _sup) or (flag in _sup)

    acc = state.get("acceptance", {})
    def _acc_flag(key: str, flag: str) -> list[str]:
        val = str(acc.get(key, "")).strip()
        if not val or not _ok(flag):
            return []
        return [flag, val]

    acc_flags = (
        _acc_flag("pt_min",      "--pt-min")  +
        _acc_flag("pt_max",      "--pt-max")  +
        _acc_flag("eta_min",     "--eta-min") +
        _acc_flag("eta_max",     "--eta-max") +
        _acc_flag("mult_low",    "--mult-low") +
        _acc_flag("mult_high",   "--mult-high") +
        _acc_flag("sphero_low",  "--sphero-low") +
        _acc_flag("sphero_high", "--sphero-high")
    )
    if acc.get("validate_graph") and _ok("--validate-graph"):
        acc_flags.append("--validate-graph")
    # Opt-in event-explorer dump; lives only on the standalone run since the
    # ladder rungs produce identical-shaped data and we don't need four copies.
    dump_n = int(acc.get("dump_events", 0) or 0)
    standalone_only_flags = (["--dump-events", str(dump_n)]
                             if dump_n > 0 and _ok("--dump-events") else [])

    wrap: list[str] = []
    if par.get("caffeinate") and shutil.which("caffeinate"):
        wrap += ["caffeinate", "-i"]
    if par.get("nice") and shutil.which("nice"):
        wrap += ["nice", "-n", "10"]

    stages  = state.get("stages", {})
    cmds: list[list[str]] = []
    generated: list[str] = []
    if pythia_cmnd is not None:
        generated.append(str(pythia_cmnd))
    if herwig_in is not None:
        generated.append(str(herwig_in))

    # Anything other than plain single-Pythia uses the per-generator layout
    # (compare/<gen>.root).  >1 generator additionally overlays them.
    gen_mode = generators != ["pythia"]
    compare_overlay = len(generators) > 1
    rungs_designed = _designed_rungs(state)
    # Cross-generator mechanism comparison: vary the SAME mechanisms (MPI/CR)
    # in every generator and overlay → compare/<gen>_<rung>.root.
    compare_mech = bool(state.get("compare_mechanisms")
                        and compare_overlay and rungs_designed)
    compare_dir = outdir / "compare"
    study = study_binary(repo)

    def _gen_run_argv(gen: str):
        """Per-generator provenance-study command for comparison mode, or None
        if that generator can't run yet."""
        out_root = compare_dir / (gen + ".root")
        base = wrap + [study, "--events", events, "--species", species,
                       "--ecm", ecm, "--seed", seed,
                       "--out", str(out_root)] + acc_flags
        if gen == "pythia":
            if pythia_cmnd is not None:
                base += ["--config", str(pythia_cmnd)]
            return base
        if gen == "herwig":
            # provenance-study consumes a HepMC3 file (Herwig → .hepmc, produced
            # via the main GUI's proven Herwig flow).  Gated by the engine
            # advertising --hepmc3 AND the user pointing at a .hepmc.
            hepmc = str(state.get("herwig_hepmc", "") or "").strip()
            if not hepmc or not herwig_supported(study):
                return None
            return base + ["--hepmc3", hepmc]
        return None

    # Resume: a unit whose <out>.root.txt already exists (under a manifest with
    # the SAME config fingerprint) is finished — skip regenerating it.
    fp = resume.fingerprint(state)
    _man = resume.read_manifest(outdir)
    resuming = bool(_man and _man.get("fingerprint") == fp)

    _ext = {"pythia": "cmnd", "herwig": "in"}

    # Chunked resume: split a long Pythia run into chunks of <= chunk_events,
    # each an independently-resumable unit, then hadd + merge the summaries.
    chunk_events = int(state.get("chunk_events", 0) or 0)
    events_int   = int(events)
    seed_int     = int(seed)
    merge_script = str(repo / "cap-merge-summaries")

    def _pythia_cmds(out_root: Path, with_dump: bool) -> list[list[str]]:
        """Commands to produce out_root from a Pythia run — a single command,
        or N chunk runs + hadd + summary-merge when chunked.  Honours resume
        (finished chunks skipped)."""
        def one(ev, sd, root, dump):
            a = wrap + [study, "--events", str(ev), "--species", species,
                        "--ecm", ecm, "--seed", str(sd),
                        "--out", str(root)] + acc_flags
            if dump:
                a += standalone_only_flags
            if pythia_cmnd is not None:
                a += ["--config", str(pythia_cmnd)]
            return a
        plan = chunk_plan(events_int, chunk_events)
        if len(plan) == 1:
            if resuming and resume.unit_complete(out_root):
                return []
            return [one(events_int, seed_int, out_root, with_dump)]
        cd = _chunk_dir(out_root)
        croots = [cd / ("c%d.root" % idx) for _ce, idx in plan]
        out: list[list[str]] = []
        for (ce, idx), croot in zip(plan, croots):
            if resuming and resume.unit_complete(croot):
                continue                              # finished chunk — skip
            out.append(one(ce, seed_int + idx, croot, with_dump and idx == 0))
        # Always (re)merge so a resumed run combines the now-complete chunks.
        out.append(["hadd", "-f", str(out_root)] + [str(c) for c in croots])
        out.append(["python3", merge_script, str(out_root) + ".txt"]
                   + [str(c) + ".txt" for c in croots])
        return out

    herwig_dir = outdir / "herwig"

    def _herwig_study(out_root: Path, hepmc: str, n_events: int) -> list[str]:
        return (wrap + [study, "--events", str(n_events), "--species", species,
                        "--ecm", ecm, "--seed", seed, "--out", str(out_root)]
                + acc_flags + ["--hepmc3", hepmc])

    def _herwig_cmds(out_root: Path, run_stem: str,
                     config_lines: list[str]) -> list[list[str]]:
        """Commands to produce out_root from Herwig: generate a .hepmc (reusing
        the main-GUI recipe via herwig_runner) then provenance-study --hepmc3.

        Chunked-resume (mirrors _pythia_cmds): when chunk_events>0 and the run
        is longer, split into N independently-resumable chunks — each its OWN
        deck (with a distinct Herwig seed = base seed + chunk index, so chunks
        are statistically independent), .run, .hepmc and .root — then hadd the
        ROOT files + merge the .root.txt summaries.  A finished chunk (its
        .root.txt present under a matching fingerprint) is skipped; a cached
        .hepmc is not regenerated.

        A user-set herwig_hepmc file overrides generation entirely (single
        unit, no chunking — we don't own how that file was produced).  Returns
        [] if the engine has no --hepmc3, or no Herwig install AND no override."""
        if not herwig_supported(study):
            return []
        override = str(state.get("herwig_hepmc", "") or "").strip()

        # ---- override: one external .hepmc, single unit ----
        if override:
            if resuming and resume.unit_complete(out_root):
                return []
            return [_herwig_study(out_root, override, events_int)]

        if not herwig_runner.herwig_available():
            return []                     # no Herwig, no override — skip

        base_stem = re.sub(r"[^A-Za-z0-9]+", "_", run_stem)
        plan = chunk_plan(events_int, chunk_events)

        # ---- single (un-chunked) unit ----
        if len(plan) == 1:
            if resuming and resume.unit_complete(out_root):
                return []
            deck = herwig_runner.build_deck(herwig_dir, base_stem,
                                            config_lines, seed=seed_int)
            generated.append(str(deck))
            hp = herwig_runner.hepmc_path(herwig_dir, base_stem)
            out: list[list[str]] = []
            if not hp.exists():           # cache: don't regenerate a finished .hepmc
                out += herwig_runner.gen_commands(herwig_dir, base_stem,
                                                  events_int)
            out.append(_herwig_study(out_root, str(hp), events_int))
            return out

        # ---- chunked-resume ----
        cd = _chunk_dir(out_root)
        croots = [cd / ("c%d.root" % idx) for _ce, idx in plan]
        out = []
        for (ce, idx), croot in zip(plan, croots):
            if resuming and resume.unit_complete(croot):
                continue                              # finished chunk — skip
            stem = "%s_c%d" % (base_stem, idx)
            deck = herwig_runner.build_deck(herwig_dir, stem, config_lines,
                                            seed=seed_int + idx)
            generated.append(str(deck))
            hp = herwig_runner.hepmc_path(herwig_dir, stem)
            if not hp.exists():
                out += herwig_runner.gen_commands(herwig_dir, stem, ce)
            out.append(_herwig_study(croot, str(hp), ce))
        # Always (re)merge so a resumed run combines the now-complete chunks.
        out.append(["hadd", "-f", str(out_root)] + [str(c) for c in croots])
        out.append(["python3", merge_script, str(out_root) + ".txt"]
                   + [str(c) + ".txt" for c in croots])
        return out

    if stages.get("standalone"):
        if compare_mech:
            # One unit per (generator, rung): vary MPI/CR identically in both.
            # Pythia rung = a .cmnd; Herwig rung = its own deck → .run → .hepmc.
            for gen in generators:
                for rung in rungs_designed:
                    out_root = compare_dir / ("%s_%s.root" % (gen, rung["name"]))
                    if gen == "pythia":
                        if resuming and resume.unit_complete(out_root):
                            continue
                        cfg = materialise_gen_rung_config(
                            state, gen, rung,
                            outdir / "configs" / ("%s_%s.%s"
                                                  % (gen, rung["name"], _ext[gen])))
                        generated.append(str(cfg))
                        cmds.append(wrap + [study, "--events", events,
                                            "--species", species, "--ecm", ecm,
                                            "--seed", seed, "--out", str(out_root)]
                                    + acc_flags + ["--config", str(cfg)])
                    elif gen == "herwig":
                        cfg_lines = (HerwigPanel.resolved_lines(state)
                                     + mechanisms.mech_lines(
                                         "herwig", rung.get("mechs", []),
                                         only=mechanisms.common_mechanisms()))
                        cmds += _herwig_cmds(out_root, "herwig_" + rung["name"],
                                             cfg_lines)
        elif gen_mode:
            for gen in generators:
                if gen == "pythia":
                    cmds += _pythia_cmds(compare_dir / "pythia.root",
                                         with_dump=False)
                elif gen == "herwig":
                    cmds += _herwig_cmds(compare_dir / "herwig.root", "herwig",
                                         HerwigPanel.resolved_lines(state))
        else:
            cmds += _pythia_cmds(pions, with_dump=True)

    if stages.get("ladder"):
        argv = wrap + [
            str(repo / PIPE_LADDER),
            "--events", events, "--species", species,
            "--ecm", ecm, "--seed", seed,
            "--jobs", jobs, "--outdir", str(ladder_dir),
        ] + acc_flags
        # The ladder is the user-designed set of rungs (Pythia tab); each rung
        # names which mechanisms are on, written in cap-mechanism-ladder's
        # "name: MECH ..." format.  The shared Pythia config is spliced into
        # every rung via --extra-cmnd.  (Per-rung 'overrides' are captured in
        # state but not emitted yet — needs the tool's per-rung override
        # support; see COORD [B] needs.)
        rungs = state.get("ladder_rungs") or [
            {"name": n, "mechs": list(m)}
            for n, m in cumulative_rungs({}).items()]
        rungs = [r for r in rungs if r.get("name")]
        if rungs:
            ladder_file = ladder_dir / "ladder.txt"
            ladder_file.parent.mkdir(parents=True, exist_ok=True)
            ladder_file.write_text(
                "# generated by cap-provenance-gui\n" +
                "".join("%s: %s\n" % (r["name"], " ".join(r.get("mechs", [])))
                        for r in rungs))
            argv += ["--ladder", str(ladder_file)]
            generated.append(str(ladder_file))
        if pythia_cmnd is not None:
            argv += ["--extra-cmnd", str(pythia_cmnd)]
        cmds.append(argv)

    if stages.get("plot"):
        argv = [str(repo / PIPE_PLOT)]
        if gen_mode:
            if compare_overlay:
                # Overlay the generators with fixed per-generator colours/labels.
                argv += ["--compare", str(compare_dir)]
            else:
                # Single non-Pythia generator: full single-run figures.
                argv += ["--root",
                         str(compare_dir / (generators[0] + ".root"))]
        else:
            if stages.get("standalone"):
                argv += ["--root", str(pions)]
            if stages.get("ladder"):
                argv += ["--ladder", str(ladder_dir)]
        argv += ["--outdir", str(plots_dir)]
        # Pair picker (multi-species): restrict which species-pair figures the
        # plotter emits.  The engine still computes every pair (the compute-
        # side --pairs flag is a pending engine feature); this just keeps the
        # figure set / report focused on the pairs the user cares about.
        pair_sel = state.get("pairs", [])
        if pair_sel:
            argv += ["--pairs", ",".join(pair_sel)]
        cmds.append(argv)

    _GEN_LABELS = {"pythia": "Pythia 8", "herwig": "Herwig 7",
                   "sherpa": "Sherpa", "epos": "EPOS"}

    if stages.get("report"):
        # In comparison mode the per-generator tables come from the primary
        # generator's summary (Pythia if present); the overlay figures show
        # both generators.
        if gen_mode:
            primary = "pythia" if "pythia" in generators else generators[0]
            summary_path = str(compare_dir / (primary + ".root")) + ".txt"
        else:
            summary_path = str(pions) + ".txt"
        report_argv = [
            report_binary(repo),
            "--summary", summary_path,
            "--figures", str(plots_dir),
            "--ladder",  str(ladder_dir / "ladder-comparison.csv"),
            "--mode",    state.get("report", {}).get("mode", "paper"),
            "--outdir",  str(reports),
        ]
        # Cross-generator COMPARISON report: when two generators ran and we
        # have a plain <gen>.root for each (the non-compare-mech overlay path),
        # feed the second summary so the report builds genealogy + pair
        # comparison tables (both generators side by side) and the compare_*
        # overlay figures.  This is ONE report; each generator still gets its
        # own individual report from a separate single-summary invocation.
        if compare_overlay and not compare_mech:
            others = [g for g in generators if g != primary]
            if others:
                second = others[0]
                second_summary = str(compare_dir / (second + ".root")) + ".txt"
                report_argv += [
                    "--summary2", second_summary,
                    "--label1", _GEN_LABELS.get(primary, primary.capitalize()),
                    "--label2", _GEN_LABELS.get(second, second.capitalize()),
                ]
        # Feed the reproducibility envelope into the report.  The C++
        # report-builder also auto-detects git SHA / hostname when these
        # are absent — passing them explicitly just gives us control.
        if pythia_cmnd is not None:
            report_argv += ["--config", str(pythia_cmnd)]
        if ladder_dir.is_dir():
            report_argv += ["--ladder-dir", str(ladder_dir)]
        cmds.append(report_argv)

    if stages.get("pdflatex") and shutil.which("pdflatex"):
        for _ in range(2):
            cmds.append(["pdflatex", "-interaction=nonstopmode",
                         "provenance-report.tex"])

    return cmds, generated


# ---------------------------------------------------------------------------
class Runner:
    """Thread-based runner.  Owns the live process; pushes stdout lines
    into `output_q`.  GUI calls `tick_callback()` on the Tk thread."""

    def __init__(self, output_q: "queue.Queue[str]"):
        self.output_q = output_q
        self.proc: subprocess.Popen | None = None
        self._lock = threading.Lock()
        self.thread: threading.Thread | None = None
        self.aborted = False

    def is_running(self) -> bool:
        return self.thread is not None and self.thread.is_alive()

    def start(self, cmds: list[list[str]], state: dict,
              on_done: Callable[[], None]) -> None:
        if self.is_running():
            return
        self.aborted = False
        self.thread = threading.Thread(
            target=self._run, args=(cmds, state, on_done), daemon=True)
        self.thread.start()

    def stop(self) -> None:
        with self._lock:
            self.aborted = True
            if self.proc is None:
                return
            try:
                if os.name == "posix":
                    os.killpg(os.getpgid(self.proc.pid), signal.SIGTERM)
                else:
                    self.proc.terminate()
            except Exception:
                pass

    # --- internals ------------------------------------------------------
    def _emit(self, text: str, tag: str = "") -> None:
        # Encode tag inline as a leading sentinel the App splits out.
        if tag:
            self.output_q.put(f"\0{tag}\0{text}")
        else:
            self.output_q.put(text)

    def _run(self, cmds: list[list[str]], state: dict,
             on_done: Callable[[], None]) -> None:
        repo: Path = state["repo"]
        reports_dir = Path(state["outdir"]) / "reports"
        for i, argv in enumerate(cmds, 1):
            if self.aborted: break
            cwd = reports_dir if argv and argv[0] == "pdflatex" else None
            self._emit(f"\n=== [{i}/{len(cmds)}] "
                       + " ".join(shell_quote(x) for x in argv) + " ===\n",
                       "stage")
            try:
                with self._lock:
                    self.proc = subprocess.Popen(
                        argv,
                        stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                        text=True, bufsize=1,
                        cwd=str(cwd) if cwd else None,
                        preexec_fn=os.setsid if os.name == "posix" else None,
                    )
                assert self.proc.stdout is not None
                for line in self.proc.stdout:
                    self._emit(line)
                rc = self.proc.wait()
                with self._lock:
                    self.proc = None
                if rc != 0:
                    self._emit(f"\nstage {i} failed (exit {rc})\n", "error")
                    break
            except FileNotFoundError as exc:
                self._emit(f"\nmissing executable: {exc}\n", "error")
                break
            except Exception as exc:                       # noqa: BLE001
                self._emit(f"\ncrash: {exc!r}\n", "error")
                break
        self._emit("\n=== pipeline finished ===\n", "stage")
        on_done()
